import './globals.css';
import Navbarin from './components/Navbar/index.tsx';
import Footer from './components/Footer/Footer.tsx';
import { cookies } from 'next/headers';
import { userAgent } from 'next/server';

export const metadata = {
  title: 'Ansuariya',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = cookies(); // Access cookies object directly
  const sessionCookie = (await cookieStore).get('wos-session')?.value || null; // Fetch the session cookie value
  console.log("Session Cookie Content:", sessionCookie);


  let userFirstName: string | null = null;

  if (sessionCookie) {
    try {
      // Validate the session and extract the user's first name
      const response = await fetch(`${process.env.NEXT_PUBLIC_API_BASE}/api/validate`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ sessionData: sessionCookie }),
        cache: 'no-store', // Prevent caching to ensure fresh data
      });

      const data = await response.json();
      // console.log("dat", data)

      if (data.authenticated) {
        userFirstName = data.user?.firstName || null;
      }
    } catch (error) {
      console.error('Failed to validate session:', error);
    }
  }

  return (
    <html lang="en">
      <body>
        {/* Pass the user's first name as a prop to Navbar */}
        <Navbarin userFirstName={userFirstName} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
